name: Qwiet

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    container:
      image: shiftleft/core:latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Run Spotless check
      run: mvn spotless:check
    - name: Run build
      run: mvn build      
    
    - name: Download ShiftLeft CLI
      run: |
        java --version
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
        tree

    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --force --wait --app Benchmark --java --cpg target/*.jar
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
